version: '3.4'

services:
  authenticationserver.web:
    image: ${DOCKER_REGISTRY-}authenticationserverweb
    build: .

  identitydb:
    image: mysql


networks:
  proxynet:
    name: custom_network
