version: '3.5'

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: ./ 
    restart: always
    ports:
      - "7000:80"
    environment:
      ASPNETCORE_URLS: "http://+"
    volumes:
      - /home/jeroen/usersecrets/6b294752-38ff-4b32-a242-41a1b4ac376d:/root/.microsoft/usersecrets/6b294752-38ff-4b32-a242-41a1b4ac376d
    depends_on:
      - db-server
    networks:
      - localdev

  db-server:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Jeroen1234
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433" 
    networks:
      - localdev