version: '3.8'

services:
  authenticationserver.web:
    image: ${DOCKER_REGISTRY-}authentication.server  
    build:
      context: .
      dockerfile: AuthenticationServer.Web/Dockerfile

  identitydb:
    image: mysql

  auth.email:
    image: booij/email.service
    
